### ISSUE TITLE
Keyboard shortcuts stop working after application restart

### ISSUE THREAD

**Issue by cmmartti** [anpho/2048-in-Cascades#5]
Start a new game. On physical-keyboard devices, AWSD can be used to control the game. Close the application with the game in progress. Open it again; the in-progress game will be continued, but keyboard shortcuts will no longer work. Starting a new game allows keyboard shortcuts to work again.

**Comment by anphorea** [comment]
Let me check this out,
thanks for response :)

**Comment by anphorea** [comment]
@cmmartti I've tested on blackberry Q10, the problem you facing is not existed on it.
could you please tell me about your device model ?

**Comment by cmmartti** [comment]
Q10SQN100-3/10.3.2.2252.The bug definitely exists, but it seems to be intermittent now that I tried it many times in a row. About 1 in 2 times the keyboard shortcuts do not work after opening the app and resuming an existing game.I also discovered that when it does happen, simply opening the Application menu at the top of the screen then closing it again one or two times is enough to get them working again.                                                                                                                                                                                                                                                                                                                                        Sent using BlackBerry Q10                                                                                                                                                                                                                From: Merrick ZhangSent: Thursday, July 23, 2015 11:21 PMTo: anpho/2048-in-CascadesReply To: anpho/2048-in-CascadesCc: cmmarttiSubject: Re: [2048-in-Cascades] Keyboard shortcuts stop working after application restart (#5)@cmmartti I've tested on blackberry Q10, the problem you facing is not existed on it.
could you please tell me about your device model ?

—Reply to this email directly or view it on GitHub.

**Comment by anphorea** [comment]
@cmmartti I added some code to prevent this, should work. new version submitted to blackberry world already and waiting approval.
please let me know if this issue remains.
p.s. new version brings in active frame update and supports only 10.3.1 + .

**Comment by anphorea** [comment]
@cmmartti I've uploaded the latest release of 2048 in blackberry beta zone, could you please help me test this release and tell me if the problem still there ?
thanks !

**Comment by cmmartti** [comment]
Good news! The problem seems to be fixed now. Keyboard shortcuts have worked perfectly ever since you released that bugfix to BlackBerry World.                                                                                                                                                                                                                                                                                                                                        Sent using BlackBerry Q10                                                                                                                                                                                                                From: Merrick ZhangSent: Friday, July 31, 2015 12:02 PMTo: anpho/2048-in-CascadesReply To: anpho/2048-in-CascadesCc: cmmarttiSubject: Re: [2048-in-Cascades] Keyboard shortcuts stop working after application restart (#5)@cmmartti I've uploaded the latest release of 2048 in blackberry beta zone, could you please help me test this release and tell me if the problem still there ?
thanks !

—Reply to this email directly or view it on GitHub.

**Comment by anphorea** [comment]
Thanks !
