### ISSUE TITLE
how can I translate your app?

### ISSUE THREAD

**Issue by TranslationGroup** [anpho/2048-in-Cascades#8]
I just downloaded your app on beta zone!
It's very great! I want translate your app, I can translate it into Arbic, Japanese, Indian, German, Portuguese, Spanish,.... help you!
If you like, plz reply or send email to me: translationsgroupbbdev@gmail.com

**Comment by anphorea** [comment]
well I've translated into several languages already, check it out in settings .

**Comment by TranslationGroup** [comment]
I only see some language, if you need more... I can help you
